# -*- coding: utf-8 -*-
"""Topsis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohrfNgBLAh6zu0HiOoNtfq0HV37yNrVg
"""

import sys
import pandas as pd
import numpy as np

def error(msg):
    print(f"Error: {msg}")
    sys.exit(1)

def read_input_file(filename):
    try:
        if filename.endswith(".csv"):
            return pd.read_csv(filename)
        elif filename.endswith(".xlsx"):
            return pd.read_excel(filename)
        else:
            error("Unsupported file format. Use .csv or .xlsx")
    except FileNotFoundError:
        error("Input file not found")

def write_output_file(df, filename):
    if filename.endswith(".csv"):
        df.to_csv(filename, index=False)
    elif filename.endswith(".xlsx"):
        df.to_excel(filename, index=False)
    else:
        error("Output file must be .csv or .xlsx")

def topsis(input_file, weights, impacts, output_file):
    df = read_input_file(input_file)

    # Check minimum columns
    if df.shape[1] < 3:
        error("Input file must contain at least 3 columns")

    alternatives = df.iloc[:, 0]
    data = df.iloc[:, 1:]

    # Check numeric values
    try:
        data = data.astype(float)
    except:
        error("From 2nd to last columns must contain numeric values only")

    # Parse weights and impacts
    try:
        weights = np.array(weights.split(','), dtype=float)
    except:
        error("Weights must be numeric and comma-separated")

    impacts = impacts.split(',')

    if len(weights) != data.shape[1] or len(impacts) != data.shape[1]:
        error("Number of weights, impacts and criteria must be equal")

    for i in impacts:
        if i not in ['+', '-']:
            error("Impacts must be either '+' or '-'")

    # Step 1: Normalize decision matrix
    norm_data = data / np.sqrt((data ** 2).sum())

    # Step 2: Weighted normalized matrix
    weighted_data = norm_data * weights

    # Step 3: Ideal best and worst
    ideal_best = []
    ideal_worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            ideal_best.append(weighted_data.iloc[:, i].max())
            ideal_worst.append(weighted_data.iloc[:, i].min())
        else:
            ideal_best.append(weighted_data.iloc[:, i].min())
            ideal_worst.append(weighted_data.iloc[:, i].max())

    ideal_best = np.array(ideal_best)
    ideal_worst = np.array(ideal_worst)

    # Step 4: Distance measures
    dist_best = np.sqrt(((weighted_data - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted_data - ideal_worst) ** 2).sum(axis=1))

    # Step 5: TOPSIS score
    topsis_score = dist_worst / (dist_best + dist_worst)

    # Step 6: Ranking
    result = df.copy()
    result["Topsis Score"] = topsis_score
    result["Rank"] = result["Topsis Score"].rank(ascending=False).astype(int)

    write_output_file(result, output_file)
    print("TOPSIS analysis completed successfully")

if __name__ == "__main__":
    if len(sys.argv) != 5:
        error("Usage: python topsis.py <InputFile> <Weights> <Impacts> <OutputFile>")

    _, input_file, weights, impacts, output_file = sys.argv
    topsis(input_file, weights, impacts, output_file)